#!/usr/bin/env bash
set -euo pipefail

START_DATE=$1
END_DATE=$2

FILED=$(python3 releng-phab-arc-queries.py --filed --start-date "$START_DATE" --end-date "$END_DATE" | \
    arc call-conduit maniphest.search | \
    jq '.response.data | length')
CLOSED=$(python3 releng-phab-arc-queries.py --closed --start-date "$START_DATE" --end-date "$END_DATE" | \
    arc call-conduit maniphest.search | \
    jq '.response.data | length')

# printf 'Tasks authored by RelEng folks: %s\nClosed tasks owned by RelEng folks: %s\n' "$FILED" "$CLOSED"
printf '%s\n%s' "$FILED" "$CLOSED"
