#!/usr/bin/env bash
set -euo pipefail
DATE=$1

header() {
    printf '== %s ==\n' "$@"
}

subheader() {
    printf '=== %s ===\n' "$@"
}

header "Random Stats"
subheader "Phab Stats"
bash phab-week-stats "$DATE"
subheader "Gerrit stats"
bash gerrit-week-stats
